package com.aspodev.parser.Instructions;

public enum InstructionTypes {
	OTHER, IMPORT_STATEMENT, PACKAGE_STATEMENT, ATTRIBUTE_DECLARATION, RECORD_DECLARATION, LOCAL_VARIABLE_DECLARATION,
	INTERFACE_DECLARATION, ENUM_DECLARTION, CLASS_DECLARATION, METHOD_DECLARATION, CONSTRUCTOR_DEFENITION, END_OF_BLOCK,
	INITIALAZATION_BLOCK, STATIC_INITIALZATION, LAMBDA_FUNCTION, GENERIC_METHOD_DECLARATION, ENUMERATOR_DECLARATION,
	SWITCH_STATEMENT, LABEL_CASE_STATEMENT, CATCH_STATEMENT, THROW_STATEMENT
}
