package com.aspodev.parser.Instructions;

public enum InstructionTypes {
	OTHER, IMPORT_STATEMENT, PACKAGE_STATEMENT, ATTRIBUTE_DECLARATION, RECORD_DEFINITION, LOCALVARIABLE_DECLARATION,
	INTERFACE_DECLARATION,
	ENUM_DECLARTION, CLASS_DECLARATION, METHOD_DECLARATION, CONSTRUCTOR_DEFENITION, END_OF_BLOCK, INITIALAZATION_BLOCK,
	STATIC_INITIALZATION, LAMBDA_FUNCTION
}
